user  nginx;
worker_processes auto;

error_log  /var/log/nginx/error.log warn;
pid        /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream backend_upstream {
        server backend:3000;
    }

    upstream frontend_upstream {
        server frontend:8080;
    }

    include /etc/nginx/conf.d/*.conf;
}
